### ISSUE TITLE
Variant images not zooming

### ISSUE THREAD

**Issue by yefb** [spree-contrib/spree_product_zoom#3]
Hello there,

I have a product that has 3 variants, all with their respective images.

The extension just zoom the images that I have defined as for All variants, but those images that are for a  specific variant are not zoomed or displayed in any way.

Just an example product: http://goo.gl/ijhXW

This has Green, Red and Silver variants and at least 18 images, but just the first two are zoomed as those are specified for All variants.

Something different happend with this product: http://goo.gl/khvZ6
This product has no variants, so, all the images is in the master variant (All variants). All the images are displayed. The only issue is that the first image is displayed twice.

Thank you.

**Comment by jddiegel** [comment]
I seem to still have this issue in 3-0-stable.  What was the resolution?
